name: Release Please

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch full history for proper conventional commit analysis
          fetch-depth: 0

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          # Use the default configuration file
          config-file: '.github/release-please-config.json'
          # Token for creating releases and PRs
          token: ${{ secrets.GITHUB_TOKEN }}
          # Ensure tags are created for releases
          include-component-in-tag: false

      - name: Create Release PR
        if: steps.release.outputs.release_created == 'true'
        run: |
          echo "Release created: ${{ steps.release.outputs.tag_name }}"
          echo "Upload URL: ${{ steps.release.outputs.upload_url }}"

      - name: Trigger Publish Workflow
        if: steps.release.outputs.release_created == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            // Trigger the publish workflow
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'publish-npm.yml',
              ref: 'master'
            });
            console.log('Triggered publish-npm.yml workflow');
